dist: bionic
language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

git:
  depth: 1

addons:
  apt:
    packages:
      - rabbitmq-server

services:
  - rabbitmq
  - redis-server
  - elasticsearch

before_install:
  - sudo service postgresql stop
  - sudo apt install -yq --no-install-suggests --no-install-recommends postgresql-11 postgresql-client-11
  - sed -e 's/^port.*/port = 5432/' /etc/postgresql/11/main/postgresql.conf > postgresql.conf
  - sudo chown postgres postgresql.conf
  - sudo mv postgresql.conf /etc/postgresql/11/main
  - sudo cp /etc/postgresql/11/main/pg_hba.conf
  - sudo service postgresql restart 11
  - sudo rabbitmqctl add_user local local
  - sudo rabbitmqctl set_user_tags local administrator
  - sudo rabbitmqctl set_permissions -p / local ".*" ".*" ".*"
  - go get -t -v ./...
  - go mod vendor

notifications:
  email: false

before_script:
  - export PATH="/usr/lib/postgresql/11/bin:$PATH"
  - psql -U postgres -c "create user forgolang login password '123456';"
  - psql -U postgres -c "create database forgolang_test owner forgolang;"
  - sleep 10

script:
  - go run ./cmd -genSecretEnv
  - go run ./cmd -mode test -migrate -reset
  - go run ./cmd -mode test -task -name GenerateBase
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
